[package]
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
categories = ["cryptography::cryptocurrencies"]
description = "Account primitives to be used in Nimiq's Albatross implementation"
edition = "2021"
homepage = "https://nimiq.com"
keywords = ["nimiq", "cryptocurrency", "blockchain"]
license = "Apache-2.0"
name = "nimiq-account"
repository = "https://github.com/nimiq/core-rs-albatross"
version = "0.1.0"

[dependencies]
hex = {version = "0.4"}
lazy_static = "1.3"
log = "0.4"
parking_lot = {git = "https://github.com/styppo/parking_lot.git"}
rand = "0.8"
serde = {version = "1.0", features = ["derive"], optional = true}
strum_macros = "0.23"
thiserror = "1.0"

beserial = {path = "../../beserial"}
beserial_derive = {path = "../../beserial/beserial_derive"}
nimiq-bls = {path = "../../bls"}
nimiq-collections = {path = "../../collections", features = ["bitset"]}
nimiq-database = {path = "../../database"}
nimiq-hash = {path = "../../hash"}
nimiq-keys = {path = "../../keys", features = ["serde-derive"]}
nimiq-macros = {path = "../../macros"}
nimiq-primitives = {path = "..", features = ["coin", "policy", "serde-derive", "slots"]}
nimiq-transaction = {path = "../transaction", features = ["serde-derive"]}
nimiq-trie = {path = "../trie"}
nimiq-utils = {path = "../../utils", features = ["hash-rng"]}
nimiq-vrf = {path = "../../vrf"}

[dev-dependencies]
hex = "0.4"
tempdir = "0.3"


nimiq-build-tools = {path = "../../build-tools"}

[features]
serde-derive = ["serde"]
